### ISSUE TITLE
Polygon AOI

### ISSUE THREAD

**Issue by etboudreau** [DSHydro/PyPlanetSCA-Python-Library#2]
Ideally you can use a polygon Area of Interest (AOI), but Planet does have some specifications you need to adhere to

AOI geometry limits per Planet documentation:
- GeoJSON Polygons with holes first will be rejected.
- GeoJSON Polygons with multiple exterior rings will be rejected.
- GeoJSON MultiPolygons with overlapping/intersecting Polygons will be rejected. The GeoJSON spec technically allows this, but is generally invalid geometry in many programs (PostGIS, Shapely, QGIS to name a few).
- GeoJSON containing more than 1,500 (or 500 I am seeing different statements on this - I was using 149 vertices and it worked) vertices will be rejected.
- Clipping outside contract AOI may result in a rejected order.

Potential solutions:
One way to simplify geometries, less ideal for reproducibility/efficient workflow (this is what I did): [Manual method - MapShaper.org](https://developers.planet.com/docs/planetschool/geojson-and-areas-of-interest-aois/)

Here is another alternative, better for package implementation (just found this, haven't tried it personally: [Python package friendly](https://developers.planet.com/blog/2022/Dec/15/simplifying-your-complex-area-of-interest-a-planet-developers-deep-dive/)

**Comment by spestana** [comment]
Thanks @etboudreau !

A couple of initial thoughts on this:
1. It would be great if a user could provide a geojson or shapefile geometry and the library will take care of any polygon simplification steps on its own (therefore the user doesn't have to worry about this)
2. The library should let a user know if their polygon has been simplified according to any of the above requirements (e.g. a warning message) so that it's not a surprise when the image output shape is different from their input polygon
3. If for some reason the library cannot simplify the polygon, it should point the user to these resources from Planet for more information

**Comment by spestana** [comment]
I've started some work on this, by re-writing how the api search filtering is being done, you can see these updates on my fork: https://github.com/spestana/PyPlanetSCA-Python-Library/blob/main/src/planetsca/search_filters.py

**Comment by IanChiu-333** [comment]
Just finished this. It's in a new branch until we figure out what's wrong with the .toml file.
