### ISSUE TITLE
Version unsynced

### ISSUE THREAD

**Issue by IanChiu-333** [DSHydro/PyPlanetSCA-Python-Library#45]
The version on the docs is not synced with the package. Possibly an issue with a setting? Hatchling creates a version file that may have a seperate counter than pypi.

**Comment by spestana** [comment]
I think the correct way to do this, is in the github workflow that creates the documentation, we should be installing planetsca from pypi, rather than locally. This way the version number from pypi is pulled in to the docs.

This also means that the docs are only updated when we create a new release - which also makes sense. The docs should reflect the functionality of the planetsca package as it's available on pypi, rather than any local development version we're working on.

We need to change [this line](https://github.com/DSHydro/planetsca/blob/main/.github/workflows/build-docs.yml#L30) to:
`pip install --extra-index-url https://test.pypi.org/simple planetsca[doc]`

And I believe that'd fix this version mismatch issue. @IanChiu-333 want to try this?

**Comment by IanChiu-333** [comment]
Yup! That was the right fix. Thanks for finding the solution.
